### ISSUE TITLE
Running a test suite results in table being dropped

### ISSUE THREAD

**Issue by adriandugan** [erikgall/eloquent-phpunit#9]
Short [video](https://www.dropbox.com/s/lipy7xfr4hrg8kk/drop_table.mov?dl=0) to demonstrate.

The test file doesn't actually have much content:

```
<?php

namespace Tests;

class ClientSchemaTest extends \EGALL\EloquentPHPUnit\EloquentTestCase
{

    protected $model = 'App\Models\Client';

    public function testTableSchema()
    {
        //
    }
}
```

I'm using Laravel v5.3.23, PHPUnit 5.6.3, eloquent-phpunit v1.0.7

**Comment by adriandugan** [comment]
I see that the `down()` function is being called in the related migration class. This is dropping the table. Yes, `artisan migrate:reset` is actioned [here](https://github.com/erikgall/eloquent-phpunit/blob/b2609f8cfb0615123bd192e149f850e5c5e492ae/src/DatabaseTestHelper.php#L26).

**Comment by adriandugan** [comment]
Now that I understand "why?", I'm closing the issue because it's expected behaviour. :)

**Comment by erikgall** [comment]
@adriandugan Sorry for the confusion. I will update the readme file with more information on setting up the testing environment. What I usually do is create a second database on my local machine  and add `<env name="DB_DATABASE" value="(db name)_testing"/>` to the `phpunit.xml` file.
